### ISSUE TITLE
这个世界会好吗 2016 unplugged 不完整

### ISSUE THREAD

**Issue by wanglelecn** [PetalsOnaWet/lizhi#1]
这首歌不完整，播放到中间就没有了。

**Comment by PetalsOnaWet** [comment]
> 这首歌不完整，播放到中间就没有了。

等我有时间排查下看看是不是资源未上传完整，你先用[https://github.com/app-AZ/njlizhi](这个库)里面的听 https://github.com/app-AZ/njlizhi
