### ISSUE TITLE
Can you share with me his email address?

### ISSUE THREAD

**Issue by cnukaus** [PetalsOnaWet/lizhi#20]
I can't find his Weixin public account now.

**Comment by PetalsOnaWet** [comment]
他公布出来的 应该也被和谐了，当时是在微信公众号上联系的，后来公众号也没了。

**Comment by what-cloud** [comment]
I am planning a blockchain channel so he can still have a channel to sale his legal music... If you still have a copy of his email, I have setup a private repo and maybe you can upload it there?

I added you as the private repo collaborate already.

**Comment by PetalsOnaWet** [comment]
You contact me via tg @n3aff

**Comment by PetalsOnaWet** [comment]
langren1993@gmail.com
