### ISSUE TITLE
使用分布式网盘btsync(Resilio Sync)进行共享

### ISSUE THREAD

**Issue by xyzddc** [PetalsOnaWet/lizhi#21]
可以考虑使用Resilio Sync 来进行共享。可以突破墙的封杀，也比较安全。

**Comment by PetalsOnaWet** [comment]
等我回家看看还能不能找到源文件，找到就搞一下。

**Comment by PetalsOnaWet** [comment]
https://link.resilio.com/#f=%E8%BF%99%E4%B8%AA%E4%B8%96%E7%95%8C%E4%B8%8D%E4%BC%9A%E5%A5%BD%E4%BA%86&sz=99E8&t=1&s=JQRUZRFVAOXFOZ2CYB3ZV4722IH5SJJ6&i=CMLOMS62YW27NPU7ZAIX5QRF3PC6ADRC6&e=1840987378&v=2.6&a=2

**Comment by PetalsOnaWet** [comment]
网址https://link.resilio.com/#f=lizhi&sz=0&t=1&s=2CRMRB5YEFGDMP3CFIXLBD4CT2A2RGLY&i=CFCCVIJKK2ESCRESKFZHXNZ5DMI7FO7ML&e=-121177423&v=2.6&a=2

只读密钥

BTMQLF3VE7Y2POYYVM4PI5W4SIPX5U777

**Comment by PetalsOnaWet** [comment]
网址https://link.resilio.com/#f=lizhi&sz=0&t=1&s=2CRMRB5YEFGDMP3CFIXLBD4CT2A2RGLY&i=CFCCVIJKK2ESCRESKFZHXNZ5DMI7FO7ML&e=-121177423&v=2.6&a=2

只读密钥

BTMQLF3VE7Y2POYYVM4PI5W4SIPX5U777
