### ISSUE TITLE
分享一下百度云盘资源吧

### ISSUE THREAD

**Issue by lunxian8** [PetalsOnaWet/lizhi#22]
2018洗心革面跨年视频：
链接:https://pan.baidu.com/s/1_Cm0KPp7p_VHmq5uGQurNA&shfl=sharepset  密码:ztco

歌曲：
链接:https://pan.baidu.com/s/14hSwlLrAtq0pCo9qff3QMQ&shfl=sharepset  密码:bj54

下载上传到网易云盘不是听歌不是很方便了？

最近状态好行，不太想听b哥了

**Comment by xuekai-china** [comment]
歌曲里的没数据

**Comment by lunxian8** [comment]
链接:https://pan.baidu.com/s/1j4nHK7EyVx_iT6x86-JRyw  密码:xqna

**Comment by lunxian8** [comment]
链接:https://pan.baidu.com/s/1WRtd_Se3Ast8hRn5MZebHA  密码:coaw

**Comment by xuekai-china** [comment]
感谢🙏

**Comment by woodongwong** [comment]
链接: https://pan.baidu.com/s/1vNPkB-z9aTyVnhb3p4oxIw  密码: f49f    《1701》wav分轨

**Comment by woodongwong** [comment]
#23

**Comment by JackyTheBest** [comment]
@lunxian8 百度云没有了，方便再传下吗 ？谢谢

**Comment by lunxian8** [comment]
> @lunxian8 百度云没有了，方便再传下吗 ？谢谢

禁止分享了，估计还要重新修改一下文件md5。。
等以后有时间整理一下分享出来

**Comment by huasuper** [comment]
我在百度网盘下载了7.2G那个，但是密码是什么？

**Comment by howey77** [comment]
这几个都不能下载了 求更新

**Comment by piupiuisland** [comment]
求助..能不能来个google drive 的分享... 百度网盘不行啊..

**Comment by piupiuisland** [comment]
求助链接分享...找哭了...

**Comment by PetalsOnaWet** [comment]
@piupiuisland 看最新README.md

**Comment by PetalsOnaWet** [comment]
看主页用夸克，百度不好搞
