### ISSUE TITLE
CD抓轨，百度网盘分享

### ISSUE THREAD

**Issue by woodongwong** [PetalsOnaWet/lizhi#23]
- 你好，郑州
- 勾三搭四
- 二零零九年十月十六日事件
- F
- 1701
- 我爱南京
- Has Man A Future
- 梵高先生
- 被禁忌的游戏

里面包含整轨和分轨文件，所以7z文件比较大，分轨文件使用flac 5级压缩。整轨文件是我从互联网上收集到的，貌似是PT80论坛之前的大佬抓的，这里感谢一下大佬。

链接: https://pan.baidu.com/s/14quUfjWJwZPFu7wCVe3VyQ 提取码: wb53  （2020.11.09更新）

之前的链接莫名失效了，我把专辑使用拼音“打了码”。

解释一下为什么使用7z？7z可以对目录进行加密，防止百度云扫描里面的目录。

解压密码：lizhi

**Comment by gaoyx416** [comment]
非常感谢您的分享，解压密码好像不对，输入lizhi都无法解压，试了几个解压缩软件都不行

**Comment by woodongwong** [comment]
> 非常感谢您的分享，解压密码好像不对，输入lizhi都无法解压，试了几个解压缩软件都不行

试试7-zip， https://www.7-zip.org/

**Comment by gaoyx416** [comment]
> > 非常感谢您的分享，解压密码好像不对，输入lizhi都无法解压，试了几个解压缩软件都不行
> 
> 试试7-zip， https://www.7-zip.org/

感謝大佬，在Mac上用7z終端命令可以

**Comment by howey77** [comment]
不能下载了 求更新 谢谢

**Comment by woodongwong** [comment]
> 不能下载了 求更新 谢谢

链接: https://pan.baidu.com/s/1oHANORvupzAbm1rV8ApPog 提取码: pp62

**Comment by solerwell** [comment]
感谢大佬。

又跟媳妇儿闹矛盾了，听听逼哥，回忆一下青春。

人生，就是一个慢慢被煽的过程啊……

**Comment by nickkking** [comment]
👍

**Comment by adaiLinux** [comment]
追更

**Comment by woodongwong** [comment]
> 追更

百度网盘已经不行了，前脚分享后脚失效

**Comment by adaiLinux** [comment]
> > 追更
> 
> 百度网盘已经不行了，前脚分享后脚失效

万恶的百度网盘  我之前收集的B歌的资源也都不让我下载了  痛斥

**Comment by woodongwong** [comment]
百度已经无法分享，即使压缩和加密，资源的哈希值已经进了小黑屋，除非我重新上传一下，使其和原来资源的hash不一致，但是我没百度会员，文件太大，即便这样做，我估计也撑不了太久。

**Comment by KyonCN** [comment]
> 百度已经无法分享，即使压缩和加密，资源的哈希值已经进了小黑屋，除非我重新上传一下，使其和原来资源的hash不一致，但是我没百度会员，文件太大，即便这样做，我估计也撑不了太久。
用Google drive 或者 onedrive

**Comment by LoHsiao** [comment]
你好啊，请问能用 阿 里 网 盘 试一下上传不加密的压缩包么。感谢！

**Comment by woodongwong** [comment]
谷歌网盘分享：https://github.com/PetalsOnaWet/lizhi/issues/42

**Comment by woodongwong** [comment]
> 你好啊，请问能用 阿 里 网 盘 试一下上传不加密的压缩包么。感谢！

阿里网盘不支持分享压缩包

**Comment by woodongwong** [comment]
阿里网盘分享：#43
