### ISSUE TITLE
百度网盘已挂，求修正

### ISSUE THREAD

**Issue by itranlin** [PetalsOnaWet/lizhi#27]
百度网盘已挂，求修正

**Comment by PetalsOnaWet** [comment]
应该被md5识别了  我压缩下试试看

**Comment by PetalsOnaWet** [comment]
链接：https://pan.baidu.com/s/1R20NQJr7Di-PoakSbBdnaA 
提取码：b2hu 
复制这段内容后打开百度网盘手机App，操作更方便哦
