### ISSUE TITLE
一个逼粉的音乐播放器

### ISSUE THREAD

**Issue by Tian-Hun** [PetalsOnaWet/lizhi#3]
https://github.com/Tian-Hun/biger-music

**Comment by PetalsOnaWet** [comment]
赞

**Comment by shuiRong** [comment]
用Telegram的朋友：[此频道](https://t.me/lizhiniubi)里有本仓库提供的音乐，支持在线点击播放和单曲循环等简单的音乐播放器功能，欢迎订阅

**Comment by Ronin-YQ** [comment]
对手机端支持不太友好，希望更新下，下拉菜单希望做一下

**Comment by chiseller** [comment]
> 用Telegram的朋友：[此频道](https://t.me/lizhiniubi)里亦有本仓库提供的音乐，支持在线点击播放、单曲循环等简单的音乐播放器功能，欢迎订阅

很赞
