### ISSUE TITLE
做了一个磁力链接

### ISSUE THREAD

**Issue by ChingLin123** [PetalsOnaWet/lizhi#39]
c46974b49478bde2b28e45090775806f3937e9a0
公网ipv4-IPV6在线做种，下完的人要做种继续分享

**Comment by weixiaosmile** [comment]
失效了

**Comment by ChingLin123** [comment]
> 失效了

没有失效，这两天我一直在做种

**Comment by cdmonkey** [comment]
确实是下载不动，一点儿动静都没有~

**Comment by ChingLin123** [comment]
> 确实是下载不动，一点儿动静都没有~

你是迅雷下载的嘛

**Comment by cdmonkey** [comment]
> > 确实是下载不动，一点儿动静都没有~
> 
> 你是迅雷下载的嘛

是的

**Comment by ChingLin123** [comment]
> > > 确实是下载不动，一点儿动静都没有~
> > 
> > 
> > 你是迅雷下载的嘛
> 
> 是的

可以用正规的BT软件，迅雷会没速度

**Comment by greatycren** [comment]
用115下 秒好

**Comment by slash09** [comment]
想找演唱会版本的...有吗?
