### ISSUE TITLE
CD抓轨，阿里网盘分享

### ISSUE THREAD

**Issue by woodongwong** [PetalsOnaWet/lizhi#43]
链接：https://www.aliyundrive.com/s/s1WQGNub55d

- 你好，郑州
- 勾三搭四
- 二零零九年十月十六日事件
- F
- 1701
- 我爱南京
- Has Man A Future
- 梵高先生
- 被禁忌的游戏

里面只包含整轨，文件是我从互联网上收集到的，貌似是PT80论坛之前的大佬抓的，这里感谢一下大佬。

阿里网盘针对分享有文件格式的限制，我在源文件开头添加了2个字节，下载下来后将其删除即可，然后将文件扩展名改为`.zip`，具体可以参考我写的这篇文章：https://github.com/woodongwong/notes/issues/65

**Comment by phoulx** [comment]
实测可用，下载的文件用Python处理很方便
```python
path = '/location/of/downloaded/file'
with open(path, 'rb') as f1:
    b = f1.read()
with open(path + 'new', 'wb') as f2:
    f2.write(b[2:])
```

**Comment by woodongwong** [comment]
资源已失效
