### ISSUE TITLE
分享来自神key的链接

### ISSUE THREAD

**Issue by nongxl** [PetalsOnaWet/lizhi#44]
李志 CD&LIVE（MP3为主，整理更新中） BPXJBO6R5MT6YMZ2SNZRGJ4P3BJ73J2EM //2019年7月26日添加
看到有朋友也分享了resillio sync的key但是由于难以长时间在线而导致key失效。上面的链接来自神key，资源长期稳定在线。
【关于神key】 http://nas.bilishare.com/shenkey/shenkey.html

**Comment by Gaohaoyang** [comment]
赞shenkey

**Comment by PetalsOnaWet** [comment]
这个好
