### ISSUE TITLE
李志音乐收集 [2004 ~ 2019] [flac / m4a / mp3] 31 张专辑 429 首 

### ISSUE THREAD

**Issue by woodongwong** [PetalsOnaWet/lizhi#45]
李志音乐收集 [2004 ~ 2019] [flac / m4a / mp3] 31 张专辑 429 首

9.6G GoogleDrive [https://drive.google.com/drive/folders/1mL3I4JgEc9EYssJhBdNWfWUeVIeg_NUv](https://drive.google.com/drive/folders/1mL3I4JgEc9EYssJhBdNWfWUeVIeg_NUv)

Source: [@t.me/la_deng](https://t.me/la_deng)  

备用链接：[https://drive.google.com/drive/folders/17yqL6gsP0zdesHwAFLasfMH3rZnm7wov](https://drive.google.com/drive/folders/17yqL6gsP0zdesHwAFLasfMH3rZnm7wov)

**Comment by duskinn** [comment]
前几天刚从某个下载博客下载，看起来完全一样，如果是楼主自己整理的结果，被人拿去引流，想想就有点生气

**Comment by woodongwong** [comment]
> 前几天刚从某个下载博客下载，看起来完全一样，如果是楼主自己整理的结果，被人拿去引流，想想就有点生气

不是我整理的。

**Comment by duskinn** [comment]
那还好，总之感谢分享

**Comment by PetalsOnaWet** [comment]
做得好

**Comment by mufanGuo** [comment]
good job,thanks!

**Comment by xxmanyue** [comment]
你好 资源失效了吗

**Comment by zhuangqingguo** [comment]
🐂🍺

**Comment by chihuatario** [comment]
感谢

**Comment by akahanaton** [comment]
感谢

**Comment by 317467756-debug** [comment]
我要专门对你说一句感谢
