### ISSUE TITLE
逼的专辑网站 https://lzzz.netlify.app/

### ISSUE THREAD

**Issue by MercuryZz** [PetalsOnaWet/lizhi#47]
按专辑分页，不开代理时能听时不能停，将就吧

**Comment by xbmlz** [comment]
https://xbmlz.github.io/2022/08/22/li-zhi/

**Comment by turkyden** [comment]
✨ 推荐一个【李志】酷炫音乐播放器

访问地址：https://github.com/turkyden/lizhi-app

- [x] 资源 Github 托管, 永久有效
- [x] CDN 全球免费加速
- [x] 在线播放
- [x] 直接下载

![image](https://user-images.githubusercontent.com/24560160/187070336-1137a71a-89b4-4fac-91e2-10cbfaba4fb5.png)

**Comment by turkyden** [comment]
> 这个棒啊，仓库没放出来吗，想抄作业🤪

感觉可以做个移动端的，我这个域名有点丑，要是能买一个 `lizhi334.com` 的域名就吊了
