### ISSUE TITLE
城通网盘503

### ISSUE THREAD

**Issue by whip1ash** [PetalsOnaWet/lizhi#48]
城通网盘503了，希望能更新一下链接

**Comment by turkyden** [comment]
✨ 推荐一个【李志】酷炫音乐播放器

访问地址：https://github.com/turkyden/lizhi-app

- [x] 资源 Github 托管, 永久有效
- [x] CDN 全球免费加速
- [x] 在线播放
- [x] 直接下载

![image](https://user-images.githubusercontent.com/24560160/187070336-1137a71a-89b4-4fac-91e2-10cbfaba4fb5.png)

**Comment by PetalsOnaWet** [comment]
收到 我会尽快修复。

**Comment by PetalsOnaWet** [comment]
看主页，用夸克
