### ISSUE TITLE
打不开啊 老哥

### ISSUE THREAD

**Issue by shexuan** [PetalsOnaWet/lizhi#5]

**Comment by liwenkang** [comment]
2019年7月2日 10:51:23
在非科学上网情况下,onedrive链接无法打开
作者可以压缩后上传到其它网盘吗?非常感谢!!!

**Comment by PetalsOnaWet** [comment]
有没有想放的网站啊。百度云？估计很快就会和谐的

**Comment by liwenkang** [comment]
不知道百度云是根据什么检测的.
如果多压缩几遍,并分别加上解压密码,会不会可以避免和谐? @PetalsOnaWet

**Comment by liwenkang** [comment]
还可以做成BT种子后,加密.

**Comment by liwenkang** [comment]
2019年7月2日 11:21:16
科学上网后onedrive还是会服务器抽风.
如果把所有歌曲文件都上传到github,是不是一个好办法呢?

**Comment by PetalsOnaWet** [comment]
> 2019年7月2日 11:21:16
> 科学上网后onedrive还是会服务器抽风.
> 如果把所有歌曲文件都上传到github,是不是一个好办法呢?

github仓库有上传大小限制。我尝试过压缩包都传不上

**Comment by liwenkang** [comment]
我之前写过一个非常简陋版的 [播放器](https://github.com/liwenkang/music_Player),歌曲也是放在 github 上了,就是歌曲加载速度非常慢.
不知道还有什么优化方法......

**Comment by PetalsOnaWet** [comment]
> 我之前写过一个非常简陋版的 [播放器](https://github.com/liwenkang/music_Player),歌曲也是放在 github 上了,就是歌曲加载速度非常慢.
> 不知道还有什么优化方法......
这个应该是受限于服务器，回头我整合下，看能不能先做一个翻墙可用的播放器

**Comment by PetalsOnaWet** [comment]
夸克网盘已上传
