### ISSUE TITLE
我觉得可以建个群，作为B哥的码农粉丝群。。

### ISSUE THREAD

**Issue by RoboYao** [PetalsOnaWet/lizhi#8]

**Comment by PetalsOnaWet** [comment]
可以啊 看看有多少人响应的。

**Comment by YJTruevoice** [comment]
+1

**Comment by liwenkang** [comment]
+1

**Comment by shuiRong** [comment]
+1

**Comment by chaoyu1999** [comment]
封群警告

**Comment by qxm1501649328** [comment]
不要太高调

**Comment by lunxian8** [comment]
来吧

**Comment by ZuJunJun** [comment]
+1

**Comment by JH46666** [comment]
+1

**Comment by 245455758** [comment]
+1

**Comment by zhang7249** [comment]
群号呢，发出来

**Comment by lunxian8** [comment]
应广大b粉要求，来唠吧
![image](https://user-images.githubusercontent.com/27261113/70032401-6471d880-15e8-11ea-88d4-342e8ea08ad9.png)

**Comment by lunxian8** [comment]
![image](https://user-images.githubusercontent.com/27261113/70032556-a1d66600-15e8-11ea-9622-b72de9f33160.png)
瞎逼得

**Comment by frostpeng** [comment]
尴尬，刚好过期了

**Comment by looogen** [comment]
> 尴尬，刚好过期了

同

**Comment by Lemons-Yang** [comment]
啊！！！过期了！！！求进！！！！

**Comment by ZuJunJun** [comment]
> 啊！！！过期了！！！求进！！！！

![image](https://user-images.githubusercontent.com/21032325/71870982-b01d2200-3152-11ea-88d0-0eae972ad8f8.png)

**Comment by Alienegra** [comment]
來了～二維碼來一個

**Comment by lunxian8** [comment]
![image](https://user-images.githubusercontent.com/27261113/72862736-2d2ac880-3d09-11ea-95ff-5f6ba011e708.png)

**Comment by nehcuh** [comment]
求更新

**Comment by qizhen816** [comment]
求更新

**Comment by RoboYao** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Shepherd <notifications@github.com&gt;
发送时间: 2020年2月10日 13:28
收件人: PetalsOnaWet/lizhi <lizhi@noreply.github.com&gt;
抄送: RoboYao <244424027@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[PetalsOnaWet/lizhi] 我觉得可以建个群，作为B哥的码农粉丝群。。 (#8)




求更新

**Comment by qizhen816** [comment]
@RoboYao 没有图

**Comment by duwanqiebi** [comment]
mark 等更新

**Comment by PetalsOnaWet** [comment]
![二维码20](https://user-images.githubusercontent.com/11361122/74334023-13464800-4dd4-11ea-9341-ad3f45ba406a.jpg)

**Comment by molvqingtai** [comment]
过期了，再来一波

**Comment by PetalsOnaWet** [comment]
@molvqingtai 
![群2](https://user-images.githubusercontent.com/11361122/74948208-f2669e00-5436-11ea-87cb-3a5ad748cf5b.jpg)

**Comment by zixufang** [comment]
过期了，再来一波

**Comment by zixufang** [comment]
能再来一次二维码吗[可怜.jpg]

**Comment by PetalsOnaWet** [comment]
![微信群24](https://user-images.githubusercontent.com/11361122/75958091-7704f200-5ef6-11ea-87a8-dc04efedf737.jpg)

**Comment by PetalsOnaWet** [comment]
想进去的可以加我微信tubiej

**Comment by zixufang** [comment]
> 想进去的可以加我微信tubiej

非常感谢！

**Comment by huasuper** [comment]
> 想进去的可以加我微信tubiej

我在百度网盘下载了7.2G那个，但是密码是什么？

**Comment by feng99** [comment]
> 想进去的可以加我微信tubiej

提示用户不存在

**Comment by PetalsOnaWet** [comment]
> > 想进去的可以加我微信tubiej
> 
> 提示用户不存在

微信号改名了，刚更新一波，berichj

**Comment by syh333221** [comment]
不行啊，找不到资源了

**Comment by daolou** [comment]
2021 年了，祝大家新年快乐，来个 二维码吧

**Comment by 8621** [comment]
我突然发现百度盘里存的逼哥的歌曲全部无法下载了，悔不当初没有下载到本地，哪个好心人看到了，拉我一把 v：PAP27149  备注 逼哥

**Comment by BinZhiZhu** [comment]
老哥们看到的 拉一把哈：WlpCMTk5NjA4MTY=

**Comment by syh333221** [comment]
怎么进群啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PetalsOnaWet/lizhi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 晚上8:40
收件人:&nbsp;"PetalsOnaWet/lizhi"<lizhi@noreply.github.com&gt;;
抄送:&nbsp;"🐣"<1753957519@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PetalsOnaWet/lizhi] 我觉得可以建个群，作为B哥的码农粉丝群。。 (#8)





 
老哥们看到的 拉一把哈：WlpCMTk5NjA4MTY=

**Comment by PetalsOnaWet** [comment]
抱歉，目前只提供TG交流渠道，微信群已死群。

**Comment by PetalsOnaWet** [comment]
https://t.me/lizhiniub  tg群组

**Comment by RoboYao** [comment]
收到！

**Comment by syh333221** [comment]
qq群吗还是什么微信群



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月22日(周日) 晚上9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PetalsOnaWet/lizhi] 我觉得可以建个群，作为B哥的码农粉丝群。。 (#8)




 收到！
